export const SLIDER_DEFS = [
  {
    id: 'w_AA',
    col: 'AA',
    label: 'Auto Access to Jobs',
    icon: 'fa-car',
    group: 'Employment',
    help: 'Number of jobs accessible by car within a 40-minute drive.',
  },
  {
    id: 'w_AT',
    col: 'AT',
    label: 'Transit Access to Jobs',
    icon: 'fa-train',
    group: 'Employment',
    help: 'Number of jobs accessible by public transit within a 60-minute ride.',
  },
  {
    id: 'w_TT',
    col: 'TT',
    label: 'Transit Stops',
    icon: 'fa-bus',
    group: 'Transportation',
    help: 'Proximity to UTA bus stops, TRAX stations, and FrontRunner stations.',
  },
  {
    id: 'w_TF',
    col: 'TF',
    label: 'Freeway Exits',
    icon: 'fa-road',
    group: 'Transportation',
    help: 'Proximity to freeway entrance and exit ramps.',
  },
  {
    id: 'w_TA',
    col: 'TA',
    label: 'Active Transportation',
    icon: 'fa-bicycle',
    group: 'Transportation',
    help: 'Proximity to separated or buffered bike lanes, and multi-use trails.',
  },
  {
    id: 'w_AC',
    col: 'AC',
    label: 'Childcare Centers',
    icon: 'fa-baby',
    group: 'Necessities',
    help: 'Proximity to licensed childcare facilities.',
  },
  {
    id: 'w_AH',
    col: 'AH',
    label: 'Healthcare Facilities',
    icon: 'fa-heart-pulse',
    group: 'Necessities',
    help: 'Proximity to hospitals, clinics, and medical facilities.',
  },
  {
    id: 'w_AE',
    col: 'AE',
    label: 'Education Institutions',
    icon: 'fa-graduation-cap',
    group: 'Necessities',
    help: 'Proximity to K-12 schools and higher education institutions.',
  },
  {
    id: 'w_AG',
    col: 'AG',
    label: 'Grocery Stores',
    icon: 'fa-cart-shopping',
    group: 'Necessities',
    help: 'Proximity to supermarkets and grocery stores.',
  },
  {
    id: 'w_AM',
    col: 'AM',
    label: 'Community Centers',
    icon: 'fa-landmark',
    group: 'Necessities',
    help: 'Proximity to community halls, recreation centers, and libraries.',
  },
  {
    id: 'w_AP',
    col: 'AP',
    label: 'Public Parks',
    icon: 'fa-tree',
    group: 'Necessities',
    help: 'Proximity to public parks and open spaces.',
  },
]

export const SCORE_COLS = SLIDER_DEFS.map(d => d.col)

export const CENTER_DEFS = [
  { id: 'w_CM', label: 'Metropolitan Centers', help: 'Regional centers designated for highest density growth and activity.' },
  { id: 'w_CU', label: 'Urban Centers', help: 'Centers serving sub-regional areas with high density commercial and housing.' },
  { id: 'w_CC', label: 'City Centers', help: 'Centers serving specific cities with moderate density and mixed use.' },
  { id: 'w_CN', label: 'Neighborhood Centers', help: 'Local centers serving immediate neighborhoods.' },
]
